# site name
siteName: Tu me manques
shortName: Home
# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon
favicon: /images/favicon.png
# unique avatar
avatarShow: false
avatarImage: /images/favicon.png

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10


# your site build time or domain buy time
siteBuildingTime: 01/15/2018


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   前端: front-end
   算法: algorithm
   后端: PM
   闲谈: casual

# Left menu of single pages settings
## Notice: faName is FontAwesome style name
leftPagesMenu:
- uri: contact
  title: 联系我
  faName: fa-rss
- uri: help
  title: 帮助
  faName: fa-question


# cover info config
coverTitle: 容我先喝杯茶
coverDescription: 一个会写着写着就跑题了的人

# sns url
sns:
  github: https://github.com/Luji151515

# your article copyright or content declare
postDeclare: 转载请注明出处  <本文内容仅作为作者个人兴趣与观点，若有不恰当之处，望不吝赐教>

# Git-pages server info
pageServerName: Coding
pageServerUrl: https://coding.net/register?key=bcace447-fa41-4579-9783-86fdf0f723e2


## Comments settings.You can choose only ONE to display.
# disqus shortName,
disqus_shortname:
gitment:
  enable: false
  githubID: 
  repo: 
  ClientID: 
  ClientSecret: 
  lazy: true

# ------------- Third part private config in theme ----------------------
# CNZZ count
cnzz_siteid: 1261190932